version: '3.7'
services:

  # RabbitMQ Instance
  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
    - 15672:15672

  postgres:
    image: bitnami/postgresql
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      POSTGRESQL_DATABASE: media
  
  minio:
    image: minio/minio
    command:
    - server
    - /data
    volumes:
    - /data
    environment:
      MINIO_ACCESS_KEY: "CHANGEME"
      MINIO_SECRET_KEY: "CHANGEME"

  ###########################################
  # Our Services
  converter:
    image: jaredallard/triton-converter:prod
    environment:
      MEDIA: 'http://twilight:8001'
      MINIO: 'http://minio:9000'
      POSTGRES: 'postgres'
      RABBITMQ: 'amqp://user:bitnami@rabbitmq'
      CONFIG_ENV: production
    volumes:
    - ./config:/mnt/config

  downloader:
    image: jaredallard/triton-downloader:prod
    environment:
      MINIO: 'http://minio:9000'
      MEDIA: 'http://twilight:8001'
      RABBITMQ: 'amqp://user:bitnami@rabbitmq'
      CONFIG_ENV: production
    volumes:
    - ./config:/mnt/config

  events:
    image: jaredallard/triton-events:prod
    environment:
      RABBITMQ: 'amqp://user:bitnami@rabbitmq'
      POSTGRES: 'postgres'
      NO_TRELLO: 'true' 
      CONFIG_ENV: production
    command: events
    ports:
    - 3401:3401 # Webhook
    volumes:
    - ./config:/mnt/config

  beholder:
    image: jaredallard/triton-beholder:prod
    environment:
      RABBITMQ: 'amqp://user:bitnami@rabbitmq'
      POSTGRES: 'postgres'
      CONFIG_ENV: production
    command: beholder
    volumes:
    - ./config:/mnt/config

  twilight:
    image: jaredallard/triton-twilight:prod
    environment:
      MINIO: 'http://minio:9000'
      RABBITMQ: 'amqp://user:bitnami@rabbitmq'
      CONFIG_ENV: production
    command: twilight
    volumes:
    - ./config:/mnt/config
